// SchemaDeclaration → the Kysely `Database` interface.
//
// The gap this closes: a Drizzle user imports the generated schema module and every query is typed
// off it; a Prisma user gets a generated client. A Kysely user got SQL and nothing else, and had to
// hand-write the row types — or run kysely-codegen, which derives them by introspecting a live
// database. Deriving them from the DECLARATION instead means no round-trip, no credentials, and no
// drift: what the runtime validates and what your queries are typed against come from one source.
//
// This is for the HOST's own queries. euroclaw's adapter deliberately speaks
// `Kysely<Record<string, Record<string, unknown>>>` — it addresses tables by name at runtime and has
// no compile-time schema to bind to. These types are for the app that wants to join, report on, or
// read euroclaw's tables directly.

import type {
	FieldAttribute,
	FieldType,
	SchemaDeclaration,
	TableSchema,
} from "@euroclaw/contracts";
import { tableOrder } from "@euroclaw/contracts";

/** The dialects the row types differ across. */
export type KyselyTypeDialect = "postgres" | "sqlite";

/**
 * What a column of each declared type reads back as, per dialect. These genuinely differ: SQLite has
 * no boolean (a driver hands back 0/1) and no timestamp (we store ISO text), while Postgres returns
 * a real boolean and a Date. Typing both as the declaration's idea of the type would be a lie in one
 * of the two.
 */
const TS_TYPE: Record<KyselyTypeDialect, Record<FieldType, string>> = {
	postgres: {
		string: "string",
		number: "number",
		boolean: "boolean",
		// Read as Date, written as either — the shape ColumnType exists for.
		date: "ColumnType<Date, Date | string, Date | string>",
		// The column is TEXT and the storage layer owns the serialization, so what comes back is
		// the JSON string — not a parsed value. Same on both dialects for that reason.
		json: "string",
	},
	sqlite: {
		string: "string",
		number: "number",
		// No native boolean: the column is an integer and the driver returns 0 or 1.
		boolean: "number",
		date: "string",
		json: "string",
	},
};

const physicalColumn = (name: string, field: FieldAttribute): string =>
	field.fieldName ?? name;

const physicalTable = (model: string, table: TableSchema): string =>
	table.modelName ?? model;

/** snake_case → PascalCase, for the interface name. */
function pascal(model: string): string {
	const name = model
		.split(/[^a-zA-Z0-9]+/)
		.filter((part) => part !== "")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
	return /^[0-9]/.test(name) ? `T${name}` : name;
}

/** A column name that is not a plain identifier has to be quoted in the interface. */
function key(column: string): string {
	return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(column)
		? column
		: JSON.stringify(column);
}

export type KyselyTypesOptions = {
	schema: SchemaDeclaration;
	dialect: KyselyTypeDialect;
};

/** Emit the Kysely table interfaces and the `Database` map. Pure — no database, no filesystem. */
export function generateKyselyTypes(options: KyselyTypesOptions): string {
	const { schema, dialect } = options;
	const order = tableOrder(schema);

	// `ColumnType` is only referenced by the postgres date mapping; importing it unconditionally
	// would be an unused import in a `noUnusedLocals` project.
	const usesColumnType = Object.values(schema).some((table) =>
		Object.values(table.fields).some((field) =>
			TS_TYPE[dialect][field.type].startsWith("ColumnType<"),
		),
	);

	const lines: string[] = [
		"// Generated by `euroclaw db generate --target kysely` — do not edit by hand.",
		"// Re-run it after changing your plugins, schema, or redaction posture.",
		"",
		`import type { ${[
			...(usesColumnType ? ["ColumnType"] : []),
			"Insertable",
			"Selectable",
			"Updateable",
		].join(", ")} } from "kysely";`,
		"",
	];

	for (const model of order) {
		const table = schema[model];
		if (table === undefined) continue;
		const name = pascal(model);

		lines.push(`export interface ${name}Table {`);
		for (const [field, attribute] of Object.entries(table.fields)) {
			const column = physicalColumn(field, attribute);
			const type = TS_TYPE[dialect][attribute.type];
			// A column that is not `required` is nullable in the database, so it reads back as null.
			// A primary-key column is never nullable regardless of how it was declared.
			const nullable =
				attribute.required !== true && attribute.primaryKey !== true;
			lines.push(`\t${key(column)}: ${type}${nullable ? " | null" : ""};`);
		}
		lines.push("}");
		// The three row shapes Kysely distinguishes — reading, inserting, updating.
		lines.push(
			`export type ${name} = Selectable<${name}Table>;`,
			`export type New${name} = Insertable<${name}Table>;`,
			`export type ${name}Update = Updateable<${name}Table>;`,
			"",
		);
	}

	lines.push(
		"/** Hand this to `new Kysely<Database>({ … })` to type your own queries against euroclaw's tables. */",
		"export interface Database {",
	);
	for (const model of order) {
		const table = schema[model];
		if (table === undefined) continue;
		lines.push(`\t${key(physicalTable(model, table))}: ${pascal(model)}Table;`);
	}
	lines.push("}", "");

	return lines.join("\n");
}
