// SchemaDeclaration → Prisma models. Lives here, beside the Prisma adapter, because everything
// in it is Prisma's syntax and Prisma's rules; @euroclaw/cli only dispatches to it.
//
// Like the Drizzle generator this never touches a database: it prints models, and `prisma migrate`
// owns the rest. Emitted WITHOUT a `datasource`/`generator` block on purpose — those carry your
// connection URL and client settings, they are yours, and a generator that overwrote them would be
// destroying configuration to publish a schema.
//
// The one genuinely fiddly part is relations. Prisma does not have a bare foreign key: a reference
// is TWO fields on the owning model (the scalar plus a relation field) AND a back-reference list on
// the target. So this collects incoming references per model before emitting anything.

import type {
	FieldAttribute,
	FieldType,
	SchemaDeclaration,
	TableSchema,
} from "@euroclaw/contracts";
import { tableOrder } from "@euroclaw/contracts";

const SCALAR: Record<FieldType, string> = {
	string: "String",
	// Float for the same reason the SQL emitter picks double precision: one declared numeric type
	// covers counters and confidence scores alike, and Int would silently truncate the latter.
	number: "Float",
	boolean: "Boolean",
	date: "DateTime",
	json: "Json",
};

/** snake_case → PascalCase, the Prisma model convention (`@@map` keeps the physical name). */
function modelName(model: string): string {
	const pascal = model
		.split(/[^a-zA-Z0-9]+/)
		.filter((part) => part !== "")
		.map((part) => part.charAt(0).toUpperCase() + part.slice(1))
		.join("");
	return /^[0-9]/.test(pascal) ? `M${pascal}` : pascal;
}

/** A relation field name that cannot collide with the scalar beside it. */
function relationField(scalar: string, target: string): string {
	const base = scalar.endsWith("Id") ? scalar.slice(0, -2) : `${scalar}Ref`;
	return base === "" ? `${target}Ref` : base;
}

/** snake_case table key → a camelCase Prisma field name for the back-relation list. */
function listField(model: string): string {
	const camel = model
		.split(/[^a-zA-Z0-9]+/)
		.filter((part) => part !== "")
		.map((part, index) =>
			index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1),
		)
		.join("");
	return `${camel}s`;
}

const physicalColumn = (name: string, field: FieldAttribute): string =>
	field.fieldName ?? name;

const physicalTable = (model: string, table: TableSchema): string =>
	table.modelName ?? model;

type Incoming = { fromModel: string; listField: string };

export type PrismaGenerateOptions = {
	schema: SchemaDeclaration;
	/** Where the keyless-model notice goes. Optional — the text says it too. */
	warn?: (message: string) => void;
};

/** Emit Prisma model blocks for a declaration. Pure — no database, no filesystem. */
export function generatePrismaSchema(options: PrismaGenerateOptions): string {
	const { schema } = options;
	const warn = options.warn ?? (() => {});

	// Back-references first: every model needs to know who points at it before it is printed.
	const incoming = new Map<string, Incoming[]>();
	for (const [model, table] of Object.entries(schema)) {
		for (const field of Object.values(table.fields)) {
			const target = field.references?.model;
			if (target === undefined || schema[target] === undefined) continue;
			const list = incoming.get(target) ?? [];
			// One list field per referencing model, named for it. A model referencing the same target
			// twice would need disambiguating relation names — flagged below rather than emitted wrong.
			list.push({ fromModel: model, listField: listField(model) });
			incoming.set(target, list);
		}
	}

	const lines: string[] = [
		"// Generated by `euroclaw db generate` — do not edit by hand.",
		"// Paste or import these models into your schema.prisma; your datasource and generator blocks",
		"// are yours and are deliberately not emitted here. `prisma migrate` owns the migration.",
		"",
	];

	for (const model of tableOrder(schema)) {
		const table = schema[model];
		if (table === undefined) continue;
		const key = Object.entries(table.fields)
			.filter(([, field]) => field.primaryKey === true)
			.map(([name]) => name);

		const body: string[] = [];
		for (const [name, field] of Object.entries(table.fields)) {
			const column = physicalColumn(name, field);
			const isKey = key.includes(name);
			const optional = field.required === true || isKey ? "" : "?";
			const attrs: string[] = [];
			if (key.length === 1 && isKey) attrs.push("@id");
			if (field.unique === true && !isKey) attrs.push("@unique");
			if (column !== name) attrs.push(`@map(${JSON.stringify(column)})`);
			body.push(
				`  ${name} ${SCALAR[field.type]}${optional}${attrs.length > 0 ? ` ${attrs.join(" ")}` : ""}`,
			);

			// The relation half of a foreign key.
			const reference = field.references;
			if (reference !== undefined && schema[reference.model] !== undefined) {
				const target = modelName(reference.model);
				body.push(
					`  ${relationField(name, reference.model)} ${target}${optional} @relation(fields: [${name}], references: [${reference.field}])`,
				);
			}
		}

		for (const back of incoming.get(model) ?? []) {
			body.push(`  ${back.listField} ${modelName(back.fromModel)}[]`);
		}

		const blockAttrs: string[] = [];
		if (key.length > 1) blockAttrs.push(`  @@id([${key.join(", ")}])`);
		// Prisma REQUIRES every model to carry an identifier (@id, @@id, or a @@unique) and refuses to
		// validate a schema containing one that doesn't. euroclaw has two such tables today —
		// pii_mapping and pii_subject, whose real key is (placeholder, scope, scopeId) but whose
		// scope columns are nullable while the container-less redaction state exists. `@@ignore` is
		// the honest encoding: the rest of the schema stays valid and usable, and these two are
		// excluded from the Prisma client — which is TRUE, they cannot be driven through Prisma until
		// that key exists. See contracts/src/governance/redact.ts.
		if (key.length === 0) {
			blockAttrs.push(
				"  /// No primary key declared — Prisma cannot model this table yet.",
				"  @@ignore",
			);
			warn(
				`prisma: "${model}" declares no primaryKey, so it is emitted with @@ignore and will NOT be in the Prisma client. euroclaw's PII vault cannot run on Prisma until that key exists.`,
			);
		}
		for (const [name, field] of Object.entries(table.fields)) {
			if (field.index === true && !key.includes(name)) {
				blockAttrs.push(
					field.unique === true
						? `  @@unique([${name}])`
						: `  @@index([${name}])`,
				);
			}
		}
		const physical = physicalTable(model, table);
		if (physical !== modelName(model)) {
			blockAttrs.push(`  @@map(${JSON.stringify(physical)})`);
		}

		lines.push(
			`model ${modelName(model)} {`,
			...body,
			...(blockAttrs.length > 0 ? ["", ...blockAttrs] : []),
			"}",
			"",
		);
	}

	return lines.join("\n");
}
